### ISSUE TITLE
Problem handling accents in WPS service titles?

### ISSUE THREAD

**Issue by fionnh** [sourcepole/qgis-wps-client#2]
When trying to connect to a WPS batch geocoder with an accent in the title ("géocodeur batch"), the following error is returned :

  self.processName = str(processDescription.at(0).toElement().elementsByTagNameNS("http://www.opengis.net/ows/1.1","Title").at(0).toElement().text()).strip()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

**Comment by hdus** [comment]
please give it a try

**Comment by fionnh** [comment]
Will do ! Though I am hardly an expert in QGIS plug-ins. I'll let you know !

**Comment by fionnh** [comment]
It works now, brilliant ! FYI, it's a WPS by the French IGN on batch geocoding. http://wxs.ign.fr/[INSERT KEY HERE]/geobatch/wps/

**Comment by hdus** [comment]
What's the key to insert?
