### ISSUE TITLE
plugin broken on Debian Testing due to QtWebkit dependency

### ISSUE THREAD

**Issue by rduivenvoorde** [sourcepole/qgis-wps-client#3]
Hi,

In Debian testing users world (to be honest, I think not a very big QGIS world...), the plugin is currently broken because of the QtWebkit dependency.

I could fix one plugin of my by using a QTextBrowser in place, but I reckon you use it to create the input forms, so that would be more difficult?

Anyway, wondering what the plans are:
- do a fix for those that lost QtWebkit?
- wait for Python3?

ps I also asked on dev list if there are some general principles on this: more plugins broke with me last days...

Regards & thanks for the plugin off course :-)
Richard

**Comment by ruester** [comment]
I got it working by installing PySide and change one line of code.

Installing PySide with `pip`:
```
pip install PySide
```

Change the import in `qgswpstools.py` to:
```
from PySide.QtWebKit import QWebView
```
